#version: "3:7"

services:

  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5433:5433'
    environment:
      - 'POSTGRES_USER=kanefer'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=Jslaelo'  